# stacker build .\environments\prod.env .\config.yaml
# stacker destroy .\environments\prod.env .\config.yaml --force

namespace: "custom-wordpress"

stacks:
  - name: PrivateVPC
    template_path: ../../modules/<INSERT YAML TEMPLATE HERE>
    description: Private VPC for Wordpress environment
    profile: ${env_profile}
  - name: BastionVPC
    template_path: ../../modules/<INSERT YAML TEMPLATE HERE>
    description: Bastion VPC for Wordpress environment
    profile: ${env_profile}
  - name: PeerVPCs
    template_path: ../../modules/<INSERT YAML TEMPLATE HERE>
    description: VPC Peering for Wordpress environment
    profile: ${env_profile}
    requires: [PrivateVPC, BastionVPC]
  - name: BastionHost
    template_path: ../../modules/<INSERT YAML TEMPLATE HERE>
    description: Bastion Host for Wordpress environment
    profile: ${env_profile}
    requires: [PeerVPCs]
  - name: Wordpress
    template_path: ../../modules/<INSERT YAML TEMPLATE HERE>
    description: Wordpress environment
    profile: ${env_profile}
    requires: [BastionHost]